# Generated by Django 4.0.3 on 2022-04-09 19:11

from django.db import migrations, models
import src.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=65)),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=1000)),
                ('date_send', models.DateTimeField(auto_now_add=True)),
                ('new', models.BooleanField(default=True)),
                ('replied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=100)),
                ('project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('project_location', models.CharField(blank=True, max_length=100, null=True)),
                ('project_pictures', models.FileField(upload_to=src.models.projectDir)),
                ('project_client', models.CharField(blank=True, max_length=100, null=True)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
