# Generated by Django 4.0.3 on 2022-04-11 01:52

from django.db import migrations, models
import django.db.models.deletion
import src.models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_pictures',
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_pictures', models.FileField(upload_to=src.models.projectDir)),
                ('project_instance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='src.project')),
            ],
        ),
    ]
